sudo: required
services:
  - docker
before_install:
  - docker build -t mukulkumra/demo-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true mukulkumra/demo-react-app npm run test -- --coverage