version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: "react-app-container"
    ports: 
      - "3000:3000"
    volumes: 
      - .:/app
      - /app/node_modules
